### ISSUE TITLE
Epic - Playlists

### ISSUE THREAD

**Issue by CoopTang** [CoopTang/play_express#28]
# Description
As a user, I want to be able to create playlists that will eventually hold songs.

# Requirements

- [x] (#22) Playlist Table
- [x] (#23) Playlist Creation Endpoint
- [x] (#24) List All Playlists Endpoint
- [x] (#25) Playlist Deletion Endpoint
- [x] (#29) Playlist Update Endpoint
- [x] (#30) Playlist Endpoints Documentation
