### ISSUE TITLE
Epic - Favorites

### ISSUE THREAD

**Issue by CoopTang** [CoopTang/play_express#3]
# Description
As a user, I want to be able to keep track of all my favorite songs. I should be able to create new favorites, delete favorites, and view all my favorites

# Requirements

- [x] (#4) Favorites Table
- [x] (#6) Favorite Creation Endpoint
- [x] (#7) Favorite Show Endpoint
- [x] (#5) List All Favorites Endpoint
- [x] (#9) Favorite Deletion Endpoint
- [x] (#16) Favorite Endpoints Documentation
